### ISSUE TITLE
Logging in from neuroglancer not working when user uses Google login

### ISSUE THREAD

**Issue by austinhoag** [BrainSharer/database_portal#4]
Currently, if a user tries to log in via the "Log in" button in the Neuroglancer window, the url that they are sent to is the local user login. If the user logs in via the local method (e.g. username password) then it works. However, if a user uses Google (or some other OAuth method we implement in the future) to log in, then they are out of luck. 

Simply changing the login URL that the neuroglancer user is redirected to when they click "Log in" to: `https://brainsharer.org/brainsharer/` will work for users that log in via google. However, it won't work for users who use the local login method.

**Comment by eddyod** [comment]
This is more of an issue with brainsharer_neuroglancer. I put in an extra login button and they should work as expected now.
