### ISSUE TITLE
New user neuroglancer URLs not showing up in portal 

### ISSUE THREAD

**Issue by austinhoag** [BrainSharer/database_portal#6]
I created a new user "testuser" and used it to create a new neuroglancer state. Upon trying to create the state I got the flash message that it was successfully created. However, I cannot see the state in the table of states while logged in as this user. I can see the url while logged in as another user "austin". The testuser is an admin user and they were granted all permissions by another admin.

**Comment by eddyod** [comment]
I'm pretty sure the user needs to have a lab assigned to them. Look at the code in neuroglancer/admin.py around line 60 at the get_queryset method. That should provide some clues.
